# 02.01 Functions

> https://docs.openbb.co/sdk/guides/basics#passing-results-to-another-function

## Iterate list

> Pass a list of items from one fucntion to a different function.

In [19]:
from openbb_terminal.sdk import openbb
import pandas as pd

### Option 1: Manually

In [2]:
openbb.stocks.ca.screener(similar = ['AAPL', 'NFLX', 'META', 'AMZN', 'MSFT', 'GOOGL', 'DIS', 'TSLA'], data_type = 'valuation')

,Ticker,Market Cap,P/E,Fwd P/E,PEG,P/S,P/B,P/C,P/FCF,EPS this Y,EPS next Y,EPS past 5Y,EPS next 5Y,Sales past 5Y,Price,Change,Volume
0,AAPL,2.341010e+12,24.26,21.74,2.73,5.94,46.84,48.46,24.23,0.089,0.0898,0.216,0.0889,0.115,148.56,0.0036,11088322.0
1,AMZN,9.751400e+11,89.06,57.53,3.43,1.94,7.16,16.62,NaN,0.549,0.8239,0.676,0.2600,0.281,96.86,0.0033,11134328.0
2,DIS,1.736000e+11,55.99,18.29,2.21,2.10,1.93,13.40,111.93,1.707,0.2928,-0.280,0.2534,0.039,97.77,-0.0010,1753659.0
3,GOOGL,1.290140e+12,20.70,19.23,2.31,4.57,5.18,11.10,20.63,0.914,0.1139,0.321,0.0895,0.233,102.04,0.0104,3997221.0
4,META,3.109200e+11,11.26,15.11,NaN,2.63,2.55,7.44,11.82,0.364,-0.1407,0.316,NaN,0.337,119.93,0.0155,7345897.0
5,MSFT,1.882350e+12,27.49,22.82,2.11,9.27,10.96,17.55,42.03,0.198,0.1709,0.243,0.1301,0.155,255.29,0.0006,3686377.0
6,NFLX,1.337200e+11,28.81,29.11,4.95,4.25,6.62,21.87,186.51,0.813,0.0170,0.905,0.0582,0.275,317.95,0.0406,2564674.0
7,TSLA,5.702100e+11,59.98,34.54,1.25,7.62,15.37,27.02,35.59,6.692,0.3729,0.486,0.4809,0.504,195.87,0.0060,18915611.0

### Option 2: Programatiacally

In [8]:
# Get all symbols from SPY ETF
symbols = openbb.etf.holdings('SPY')
symbols

                                     Name % Of Etf     Shares
Symbol
AAPL                           Apple Inc.    6.40%  169769054
MSFT                Microsoft Corporation    5.38%   83812577
AMZN                     Amazon.com, Inc.    2.46%   99627185
GOOGL                      Alphabet, Inc.    1.71%   67398715
BRK.B             Berkshire Hathaway Inc.    1.71%   20282728
...                                   ...      ...        ...
COF     Capital One Financial Corporation    0.12%    4318900
CTAS                   Cintas Corporation    0.12%     967820
NUE                     Nucor Corporation    0.12%    2946140
O               Realty Income Corporation    0.12%    6949177
MNST         Monster Beverage Corporation    0.12%    4328003

[200 rows x 3 columns]

In [20]:
# Get Symbol tickers and display the top 10 items
dia_symbols = list(symbols.index.drop(['N/A']))
pd.DataFrame(dia_symbols, columns=['Tickers']).head(10)

  Tickers
0    AAPL
1    MSFT
2    AMZN
3   GOOGL
4   BRK.B
5    GOOG
6     UNH
7    TSLA
8     JNJ
9     XOM

In [16]:
# Pass list from step above as input to screener and display the top 10 items
dia_valuation = openbb.stocks.ca.screener(similar = dia_symbols, data_type = 'valuation')
dia_valuation.head(10)

,Ticker,Market Cap,P/E,Fwd P/E,PEG,P/S,P/B,P/C,P/FCF,EPS this Y,EPS next Y,EPS past 5Y,EPS next 5Y,Sales past 5Y,Price,Change,Volume
0,A,4.633000e+10,37.08,24.95,3.10,6.76,9.07,43.01,56.91,0.710,0.1083,0.229,0.1197,0.085,155.39,0.0026,155427.0
1,AAPL,2.341010e+12,24.26,21.74,2.73,5.94,46.84,48.46,24.23,0.089,0.0898,0.216,0.0889,0.115,147.25,-0.0053,13852335.0
2,ABBV,2.857600e+11,21.47,13.95,NaN,4.94,17.85,24.06,23.68,1.370,-0.1673,0.122,-0.0040,0.170,161.74,0.0034,760927.0
3,ABT,1.855400e+11,24.16,24.53,2.91,4.12,5.29,18.73,35.29,0.570,-0.1606,0.407,0.0830,0.156,108.19,0.0057,525687.0
4,ACN,1.989400e+11,28.09,23.89,2.52,3.23,8.61,25.20,31.24,0.170,0.1090,0.145,0.1116,0.112,303.30,0.0079,208546.0
5,ADBE,1.580200e+11,34.01,22.68,2.58,9.19,11.25,27.41,22.17,-0.076,0.1157,0.340,0.1319,0.219,347.35,0.0070,495649.0
6,ADI,8.802000e+10,47.61,16.14,3.20,7.93,2.41,59.85,39.44,0.516,0.0739,0.181,0.1487,0.180,170.99,-0.0054,396328.0
7,ADM,5.405000e+10,13.46,14.64,1.51,0.55,2.28,49.18,28.31,0.525,-0.1163,0.172,0.0890,0.065,93.81,-0.0378,536020.0
8,ADP,1.093200e+11,36.59,29.30,2.45,6.48,42.53,88.72,60.29,0.154,0.1108,0.120,0.1496,0.059,268.40,0.0161,193433.0
9,ADSK,4.621000e+10,71.23,27.30,3.46,9.43,59.22,30.30,29.22,-0.588,0.1206,0.234,0.2057,0.166,206.43,0.0222,255772.0

In [12]:
# Sort dataframe from screener based on Price and display the top 10 items
dia_valuation_price = dia_valuation.sort_values(by = ['Price'], ascending = False).convert_dtypes()
dia_valuation_price.head(10)

,Ticker,Market Cap,P/E,Fwd P/E,PEG,P/S,P/B,P/C,P/FCF,EPS this Y,EPS next Y,EPS past 5Y,EPS next 5Y,Sales past 5Y,Price,Change,Volume
25,AZO,49180000000.0,21.85,18.0,1.65,3.03,<NA>,186.01,19.37,0.231,0.1564,0.216,0.1325,0.083,2573.88,-0.002,18179
30,BKNG,79750000000.0,34.14,17.11,0.67,4.98,22.42,8.73,18.69,1.131,0.246,-0.08,0.5095,0.004,2091.74,0.0059,48155
44,CMG,45020000000.0,56.63,37.77,2.07,5.35,19.41,57.43,49.88,0.829,0.2894,0.971,0.274,0.141,1625.23,-0.0011,51446
143,ORLY,54180000000.0,26.39,23.32,2.42,3.85,<NA>,807.46,21.64,0.321,0.131,0.237,0.109,0.092,859.44,-0.0059,34454
158,REGN,83410000000.0,15.86,17.96,<NA>,6.08,3.75,11.88,16.44,1.358,-0.0274,0.564,<NA>,0.27,753.66,0.0026,47625
31,BLK,107120000000.0,19.73,21.3,<NA>,5.75,2.9,15.76,71.94,0.2,-0.0156,0.15,-0.0084,0.096,719.84,0.0054,90205
69,EQIX,62420000000.0,90.39,77.21,3.48,8.79,5.69,<NA>,<NA>,0.323,0.125,0.279,0.26,0.129,704.78,0.0205,60304
178,TMO,218700000000.0,31.49,24.09,7.02,4.95,5.04,<NA>,42.39,0.218,0.0099,0.307,0.0449,0.165,563.09,0.0051,137131
23,AVGO,232330000000.0,24.0,13.6,1.58,7.33,10.69,23.29,27.35,1.371,0.0821,0.4,0.152,0.157,549.41,-0.0029,193592
90,HUM,68650000000.000008,24.94,19.61,1.7,0.75,4.28,5.06,8.58,-0.105,0.1185,0.41,0.1471,0.088,545.96,-0.0072,183838

In [14]:
# Sort dataframe from screener based on Market Cap and display the top 10 items
dia_valuation_cap = dia_valuation.sort_values(by = ['Market Cap'], ascending = False).convert_dtypes()
dia_valuation_cap.head(10)

,Ticker,Market Cap,P/E,Fwd P/E,PEG,P/S,P/B,P/C,P/FCF,EPS this Y,EPS next Y,EPS past 5Y,EPS next 5Y,Sales past 5Y,Price,Change,Volume
1,AAPL,2341010000000.0,24.26,21.74,2.73,5.94,46.84,48.46,24.23,0.089,0.0898,0.216,0.0889,0.115,147.81,-0.0015,12356102
129,MSFT,1882350000000.0,27.49,22.82,2.11,9.27,10.96,17.55,42.03,0.198,0.1709,0.243,0.1301,0.155,254.23,-0.0036,4031850
83,GOOG,1312070000000.0,19.85,19.18,2.22,4.65,5.19,<NA>,<NA>,-0.159,0.121,0.2848,0.0895,<NA>,101.9,0.0044,3555759
84,GOOGL,1290140000000.0,20.7,19.23,2.31,4.57,5.18,11.1,20.63,0.914,0.1139,0.321,0.0895,0.233,101.54,0.0054,4397398
18,AMZN,975140000000.0,89.06,57.53,3.43,1.94,7.16,16.62,<NA>,0.549,0.8239,0.676,0.26,0.281,96.76,0.0023,12082437
181,TSLA,570210000000.0,59.98,34.54,1.25,7.62,15.37,27.02,35.59,6.692,0.3729,0.486,0.4809,0.504,195.54,0.0043,20034869
184,UNH,505400000000.0,26.83,21.96,1.89,1.6,6.86,13.01,19.81,0.128,0.1321,0.201,0.1422,0.092,542.56,-0.0095,398103
99,JNJ,464880000000.0,24.78,17.17,6.79,4.84,6.27,13.64,74.74,0.447,0.0319,0.057,0.0365,0.055,178.21,0.0012,890952
196,XOM,460800000000.0,9.08,9.74,0.35,1.19,2.5,15.15,10.32,2.022,-0.1786,0.234,0.258,0.066,111.3,-0.0004,1910321
195,WMT,411720000000.0,47.1,23.16,10.84,0.69,5.38,29.57,<NA>,0.027,0.0844,0.021,0.0434,0.033,151.15,-0.0083,1108588

In [15]:
# Sort dataframe from screener based on Change in Volume and display the top 10 items
dia_valuation_cap = dia_valuation.sort_values(by = ['Volume'], ascending = False).convert_dtypes()
dia_valuation_cap.head(10)

,Ticker,Market Cap,P/E,Fwd P/E,PEG,P/S,P/B,P/C,P/FCF,EPS this Y,EPS next Y,EPS past 5Y,EPS next 5Y,Sales past 5Y,Price,Change,Volume
181,TSLA,570210000000.0,59.98,34.54,1.25,7.62,15.37,27.02,35.59,6.692,0.3729,0.486,0.4809,0.504,195.54,0.0043,20034869
1,AAPL,2341010000000.0,24.26,21.74,2.73,5.94,46.84,48.46,24.23,0.089,0.0898,0.216,0.0889,0.115,147.81,-0.0015,12356102
18,AMZN,975140000000.0,89.06,57.53,3.43,1.94,7.16,16.62,<NA>,0.549,0.8239,0.676,0.26,0.281,96.76,0.0023,12082437
15,AMD,123280000000.0,46.54,21.25,3.15,5.4,2.3,22.05,36.17,0.247,0.0387,0.446,0.1479,0.309,78.29,0.0085,11421805
73,F,56040000000.0,6.28,8.13,0.75,0.37,1.33,1.4,68.1,0.252,-0.1416,0.311,0.0833,-0.021,14.3,0.0284,9781768
49,CRM,157100000000.0,299.53,28.54,19.9,5.36,2.66,11.61,27.65,-0.663,0.1866,0.263,0.1505,0.257,143.93,-0.1018,9626199
139,NVDA,404180000000.0,71.98,39.0,3.38,14.15,19.68,30.75,91.28,1.231,0.331,0.431,0.213,0.313,170.56,0.0079,8678032
119,META,310920000000.0,11.26,15.11,<NA>,2.63,2.55,7.44,11.82,0.364,-0.1407,0.316,<NA>,0.337,119.89,0.0152,7837281
27,BAC,302680000000.0,11.97,10.18,2.02,5.04,1.28,0.35,729.35,0.907,0.1629,0.191,0.0593,-0.014,36.94,-0.024,5169290
93,INTC,124730000000.0,9.28,16.02,<NA>,1.79,1.24,5.53,17.97,-0.016,-0.0404,0.181,<NA>,0.059,30.02,-0.0017,4888871